# SIM_MurmurNet Configuration File
# Basic configuration for running the emergent AI simulation

# Memory configuration
memory:
  mode: "local"  # Options: "local", "redis"
  # redis_url: "redis://localhost:6379"  # Only needed if mode is "redis"

# Model configuration
model:
  path: "google/gemma-3-1b-it"  # Model path or identifier
  quantize: "q4"                # Quantization level
  n_ctx: 512                    # Context window size

# Runtime configuration
runtime:
  threads: 4                    # Number of threads to use

# Agent configuration
agent:
  n: 3                          # Number of agents

# Prompt configuration
prompts:
  initial:
    - "Let's discuss artificial intelligence and its potential applications."
    - "What are the key challenges in machine learning today?"
    - "How can we improve human-AI collaboration?"

# Simulation configuration
simulation:
  max_iterations: 10            # Maximum number of simulation iterations
  iteration_delay: 2            # Delay between iterations in seconds
