agent:
  max_turns: -1
  n: 5
  roles:
  - 質問者
  - 回答者
  - 批評者
  - 分析者
  - 統合者
controller:
  Kd: 0.05
  Ki: 0.01
  Kp: 0.1
  target_H: 5.0
lambda:
  a: 0.4
  c: 0.2
  s: 0.15
memory:
  mode: local
  redis_url: null
metrics:
  port: 7861
model:
  path: scripts/models/gemma3-1b/gemma-3-1b-it-q4_0.gguf
  quantize: q4
prompts:
  initial:
  - こんにちは、私は質問者です。今日のトピックについて議論しましょう。
  - こんにちは、私は回答者です。どのようなご質問でもお答えします。
  - こんにちは、私は批評者です。議論の質を高めるためにコメントします。
  - こんにちは、私は分析者です。データと論理で物事を分析します。
  - こんにちは、私は統合者です。みんなの意見をまとめて新しい洞察を提供します。
rag:
  backend: chroma
  config:
    persist_directory: ./chroma_db
  enabled: false
runtime:
  threads: 6
ui:
  enabled: true
  port: 8000
