# Enhanced SLM Emergent AI Configuration
model:
  path: "C:\\Users\\園木優陽\\OneDrive\\デスクトップ\\slm_emergent_ai\\scripts\\models\\gemma3-1b\\gemma-3-1b-it-q4_0.gguf"
  quantize: "q4"

agent:
  n: 5
  max_turns: 15
  roles:
    - "Agent" # Simplified to a single, generic role

lambda:
  a: 0.4
  c: 0.4
  s: 0.2

memory:
  mode: "local"
  redis_url: null

controller:
  target_H: 6.0
  Kp: 0.15
  Ki: 0.02
  Kd: 0.08

metrics:
  port: 7861

ui:
  enabled: true
  port: 7860

rag:
  enabled: true
  backend: "chroma"
  config:
    persist_directory: "./chroma_db"

runtime:
  threads: 8

prompts:
  system: "You are an intelligent AI agent participating in a collaborative emergent intelligence system."