# 長時間実行設定ファイル - 永続的シミュレーション用
# 
# 長時間実行・反復実行専用の設定

# SLM Emergent AI 長時間実行設定
model:
  path: "scripts/models/gemma3-1b/gemma-3-1b-it-q4_0.gguf"
  quantize: "q4"

agent:
  n: 5               # エージェント数を増加
  max_turns: -1      # -1で無限ループ
  continuous: true   # 連続実行モード
  restart_interval: 100  # 100ターン毎にリスタート
  roles:
    - "質問者"
    - "回答者"
    - "批評者" 
    - "分析者"
    - "統合者"

lambda:
  a: 0.3
  c: 0.3
  s: 0.1
  dynamic: true      # 動的λ調整

memory:
  mode: "local"
  redis_url: null
  persist: true      # メモリ永続化
  checkpoint_interval: 50  # 50ターン毎にチェックポイント

controller:
  target_H: 5.0
  Kp: 0.1
  Ki: 0.01
  Kd: 0.05
  adaptive: true     # 適応的制御

metrics:
  port: 7861
  log_interval: 10   # 10ターン毎にログ出力
  save_metrics: true # メトリクス保存

ui:
  enabled: true
  port: 7860
  auto_refresh: 5    # 5秒間隔でUI更新

rag:
  enabled: false
  backend: "chroma"
  config:
    persist_directory: "./chroma_db"

runtime:
  threads: 6
  max_memory_gb: 8   # 最大メモリ使用量
  gc_interval: 100   # ガベージコレクション間隔

prompts:
  initial:
    - "長期間の議論を開始します。持続可能なAI協調について話し合いましょう。"
    - "継続的な学習と適応について考察します。"
    - "創発的知能の長期的な発展について分析します。"
    - "システムの安定性と革新性のバランスを評価します。"
    - "これまでの議論を統合し、新たな洞察を提供します。"

# 長時間実行用の特別設定
simulation:
  mode: "continuous"     # 連続実行モード
  save_state: true       # 状態保存
  auto_restart: true     # 自動再起動
  max_runtime_hours: 24  # 最大実行時間（時間）
  checkpoint_dir: "./checkpoints"  # チェックポイント保存先
